version: '3.9'

services:
  database:
    image: postgres:15.2-alpine
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
